import React, { useState, useEffect, useMemo } from "react";
import { Sparkles, HelpCircle, Feather, CheckCircle2, AlertCircle } from "lucide-react";
import { PatternSettings, Preset } from "./types";
import { PatternGenerator } from "./generator";
import { DEMO_PRESETS } from "./presets";
import PatternPreview from "./components/PatternPreview";
import ControlPanel from "./components/ControlPanel";

const LOCAL_STORAGE_KEY = "svg_pattern_custom_user_presets";

const INITIAL_SETTINGS: PatternSettings = {
  type: "rosace",
  repetitions: 12,
  symmetry: 6,
  density: 0.6,
  strokeWidth: 2.0,
  spacing: 0.25,
  rotation: 0,
  scale: 1.0,
  complexity: 4,
  seed: 120,
  canvasSize: 800,
  inverted: false,
};

export default function App() {
  const [settings, setSettings] = useState<PatternSettings>(INITIAL_SETTINGS);
  const [userPresets, setUserPresets] = useState<Preset[]>([]);
  const [notification, setNotification] = useState<{
    message: string;
    type: "success" | "info";
  } | null>(null);
  const [showHowTo, setShowHowTo] = useState(false);

  // Hook up local storage to retrieve user preset configurations
  useEffect(() => {
    try {
      const stored = localStorage.getItem(LOCAL_STORAGE_KEY);
      if (stored) {
        setUserPresets(JSON.parse(stored));
      }
    } catch (e) {
      console.error("Failed to parse cached presets:", e);
    }
  }, []);

  // Compute the live SVG markup dynamically in real-time
  const svgMarkup = useMemo(() => {
    return PatternGenerator.generate(settings);
  }, [settings]);

  // Command notifications trigger
  const triggerNotification = (message: string, type: "success" | "info" = "success") => {
    setNotification({ message, type });
    // Clear toast auto-fading
    const handler = setTimeout(() => {
      setNotification(null);
    }, 4000);
    return () => clearTimeout(handler);
  };

  // Modify individual parameters
  const handleSettingsChange = (updated: Partial<PatternSettings>) => {
    setSettings((prev) => ({ ...prev, ...updated }));
  };

  // Completely reset settings back to default parameters
  const handleResetSettings = () => {
    setSettings(INITIAL_SETTINGS);
    triggerNotification("Settings reset to standard values.", "info");
  };

  // Fire fully random seeds and parameters
  const handleRandomizeAll = () => {
    const randomSeeds = Math.floor(Math.random() * 9999) + 1;
    // Keep parameters balanced so randomization generates visually elegant motifs (guarantees quality)
    const types: PatternSettings["type"][] = [
      "rosace",
      "mandala",
      "fractal",
      "tessellation",
      "grid",
      "radial",
      "symmetry",
      "generative",
      "topography",
    ];
    const chosenType = types[Math.floor(Math.random() * types.length)];

    setSettings({
      type: chosenType,
      repetitions: Math.floor(Math.random() * 40) + 6,
      symmetry: Math.floor(Math.random() * 12) + 4,
      density: parseFloat((Math.random() * 0.7 + 0.2).toFixed(2)),
      strokeWidth: parseFloat((Math.random() * 3.5 + 1.0).toFixed(1)),
      spacing: parseFloat((Math.random() * 0.6 + 0.1).toFixed(2)),
      rotation: Math.floor(Math.random() * 180),
      scale: parseFloat((Math.random() * 0.4 + 0.8).toFixed(2)),
      complexity: Math.floor(Math.random() * 5) + 3,
      seed: randomSeeds,
      canvasSize: 800,
      inverted: Math.random() > 0.65, // Randomly invert contrast
    });

    triggerNotification("New random generative pattern activated!");
  };

  // Save customized layout to local storage
  const handleSavePreset = (name: string) => {
    const newPreset: Preset = {
      id: `preset-${Date.now()}`,
      name,
      description: `Format of type ${settings.type.toUpperCase()} generated by seed ${settings.seed}`,
      settings: { ...settings },
    };

    const updated = [...userPresets, newPreset];
    setUserPresets(updated);
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(updated));
    triggerNotification(`Pattern "${name}" successfully saved locally!`);
  };

  // Delete local preset
  const handleDeletePreset = (id: string) => {
    const filtered = userPresets.filter((p) => p.id !== id);
    setUserPresets(filtered);
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(filtered));
    triggerNotification("Local preset deleted successfully.");
  };

  // Load a preset
  const handleLoadPreset = (preset: Preset) => {
    setSettings(preset.settings);
    triggerNotification(`Preset "${preset.name}" loaded!`);
  };

  return (
    <div className="min-h-screen lg:h-screen bg-gray-50 text-gray-900 flex flex-col font-sans transition-all duration-300 lg:overflow-hidden">
      {/* GLOBAL TOAST FLOATING BANNER */}
      {notification && (
        <div className="fixed top-5 left-1/2 transform -translate-x-1/2 z-50 animate-bounce">
          <div className="flex items-center gap-2 bg-black text-white px-5 py-3 rounded-full border border-gray-800 shadow-xl max-w-sm sm:max-w-md backdrop-blur-md bg-black/90">
            {notification.type === "success" ? (
              <CheckCircle2 size={16} className="text-emerald-400 shrink-0" />
            ) : (
              <AlertCircle size={16} className="text-amber-400 shrink-0" />
            )}
            <span className="font-semibold text-xs tracking-wide">{notification.message}</span>
          </div>
        </div>
      )}

      {/* HEADER SECTION */}
      <header className="border-b border-gray-150/75 bg-white py-4 px-6 sm:px-8 shadow-xs sticky top-0 z-40 backdrop-blur-md bg-white/90 shrink-0">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          {/* Logo & Slogan */}
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-black text-white flex items-center justify-center rounded-xl font-display font-medium text-lg shadow-md select-none">
              ❖
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="font-display font-bold text-lg tracking-tight text-gray-900">
                  SVG Pattern Generator
                </h1>
                <span className="text-[10px] bg-black text-white px-2 py-0.5 rounded-full font-mono">
                  v1.3
                </span>
              </div>
              <p className="text-xs text-gray-500 font-medium">
                Create, customize, and export geometric vector patterns.
              </p>
            </div>
          </div>

          {/* Quick Guidance Actions */}
          <div className="flex items-center gap-2.5">
            <button
              onClick={() => setShowHowTo(!showHowTo)}
              className="px-3.5 py-2 hover:bg-gray-50 rounded-xl border border-gray-200 flex items-center gap-2 text-xs font-semibold text-gray-700 transition-smooth"
            >
              <HelpCircle size={15} />
              <span>{showHowTo ? "Hide Guide" : "Quick Start Guide"}</span>
            </button>
            <button
              onClick={handleRandomizeAll}
              className="px-4 py-2 bg-black hover:bg-gray-800 text-white rounded-xl flex items-center gap-2 text-xs font-semibold tracking-wider uppercase transition-smooth shadow-md"
            >
              <Sparkles size={15} />
              <span>Generate Instinctively</span>
            </button>
          </div>
        </div>
      </header>

      {/* GUIDE COLLAPSIBLE HERO FRAME */}
      {showHowTo && (
        <section className="bg-black text-gray-100 border-b border-gray-900 py-6 px-6 sm:px-8 shrink-0">
          <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="flex items-start gap-4">
              <div className="w-8 h-8 rounded-lg bg-gray-800 text-white flex items-center justify-center font-bold text-xs shrink-0 select-none">
                1
              </div>
              <div>
                <h4 className="font-display font-bold text-sm text-white mb-1">
                  Choose Your Algorithm
                </h4>
                <p className="text-xs text-gray-400 leading-relaxed">
                  Choose from 9 distinct mathematical models, including the all-new{" "}
                  <strong>Topography</strong> contour curves and river currents.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-4">
              <div className="w-8 h-8 rounded-lg bg-gray-800 text-white flex items-center justify-center font-bold text-xs shrink-0 select-none">
                2
              </div>
              <div>
                <h4 className="font-display font-bold text-sm text-white mb-1">
                  Adjust the Sliders
                </h4>
                <p className="text-xs text-gray-400 leading-relaxed">
                  Control width, symmetry, scale, and density parameters to morph your generative
                  artwork live on your screen.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-4">
              <div className="w-8 h-8 rounded-lg bg-gray-800 text-white flex items-center justify-center font-bold text-xs shrink-0 select-none">
                3
              </div>
              <div>
                <h4 className="font-display font-bold text-sm text-white mb-1">
                  Export Without Limits
                </h4>
                <p className="text-xs text-gray-400 leading-relaxed">
                  Copy SVG source code directly into your code projects, or download high-resolution
                  vector (.svg) / raster (.png) files with a single click.
                </p>
              </div>
            </div>
          </div>
        </section>
      )}

      {/* CORE CONTENT LAYOUT */}
      <main className="flex-1 w-full max-w-7xl mx-auto px-4 sm:px-6 py-4 md:py-6 grid grid-cols-1 lg:grid-cols-12 gap-6 md:gap-8 items-stretch lg:h-0 lg:overflow-hidden">
        {/* LEFT COLUMN: LIVE WORKSPACE CANVAS RENDERING (lg:7 cols) - Fixed drawing area, fully visible */}
        <section className="lg:col-span-7 flex flex-col h-full overflow-hidden select-none">
          <PatternPreview
            svgString={svgMarkup}
            settings={settings}
            onShowNotification={(msg) => triggerNotification(msg, "success")}
          />
        </section>

        {/* RIGHT COLUMN: CONTROLS & SECTOR EDITORS (lg:5 cols) - Scrollable list */}
        <section className="lg:col-span-5 h-full lg:overflow-y-auto pr-1 flex flex-col gap-6 scrollbar-thin scrollbar-thumb-gray-200 scrollbar-track-transparent">
          <ControlPanel
            settings={settings}
            onChange={handleSettingsChange}
            onReset={handleResetSettings}
            onRandomize={handleRandomizeAll}
            onSavePreset={handleSavePreset}
            presets={DEMO_PRESETS}
            userPresets={userPresets}
            onLoadPreset={handleLoadPreset}
            onDeletePreset={handleDeletePreset}
          />
        </section>
      </main>

      {/* MINIMAL FOOTER CRADLE */}
      <footer className="w-full py-3 px-6 border-t border-gray-150/75 bg-white text-center text-xs text-gray-500 shrink-0">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-1.5 justify-center">
            <Feather size={13} className="text-gray-400" />
            <span>SVG Pattern Generator — Interactive geometric and generative art</span>
          </div>
          <div className="flex items-center gap-1 font-mono text-[10px]">
            <span>
              Engine Status: <strong className="text-gray-700">READY</strong>
            </span>
          </div>
        </div>
      </footer>
    </div>
  );
}
